"""
Test dHash distance between an uploaded image and all fixtures.

Usage:
    python -m app.tools.test_dhash --image path/to/receipt.jpg
    python -m app.tools.test_dhash --image path/to/receipt.jpg --max-dist 14
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path
from app.utils.hashing import sha256_file, dhash_hex, hamming_distance_hex
from app.core.config import settings

def main() -> None:
    ap = argparse.ArgumentParser(description="Test dHash distance for receipt matching")
    ap.add_argument("--image", required=True, help="Path to receipt image")
    ap.add_argument("--max-dist", type=int, default=None, help="Max distance threshold (default: from config)")
    args = ap.parse_args()

    image_path = Path(args.image)
    if not image_path.exists():
        raise SystemExit(f"Image not found: {image_path}")

    max_dist = args.max_dist if args.max_dist is not None else settings.OCR_DHASH_MAX_DISTANCE

    print(f"Testing dHash matching for: {image_path}")
    print(f"Max distance threshold: {max_dist}")
    print("-" * 60)

    # Calculate hashes for uploaded image
    img_sha = sha256_file(image_path)
    img_dh = dhash_hex(image_path)
    print(f"Image SHA256: {img_sha[:16]}...")
    print(f"Image dHash:  {img_dh}")
    print()

    # Load fixtures
    fixtures = []
    for p in sorted(settings.FIXTURE_DIR.glob("*.json")):
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
            fixtures.append({
                "id": data.get("id", p.stem),
                "sha256": data.get("sha256", ""),
                "dhash": data.get("dhash", ""),
                "path": p
            })
        except Exception as e:
            print(f"⚠️  Failed to load fixture {p}: {e}")
            continue

    if not fixtures:
        print("❌ No fixtures found!")
        return

    print(f"Found {len(fixtures)} fixture(s):\n")

    # Check SHA256 match first
    sha256_match = None
    for f in fixtures:
        if f["sha256"] == img_sha:
            sha256_match = f
            break

    if sha256_match:
        print(f"✅ EXACT MATCH (SHA256): {sha256_match['id']}")
        print(f"   Distance: 0 (perfect match)")
        return

    # Check dHash distances
    matches = []
    for f in fixtures:
        if not f["dhash"] or f["dhash"] == "<auto-generated>":
            print(f"⚠️  {f['id']}: dHash not set (run register_fixture first)")
            continue

        try:
            dist = hamming_distance_hex(img_dh, f["dhash"])
            matches.append((f, dist))
        except Exception as e:
            print(f"⚠️  {f['id']}: Error calculating distance: {e}")
            continue

    if not matches:
        print("❌ No valid fixtures to compare!")
        return

    # Sort by distance
    matches.sort(key=lambda x: x[1])

    print("dHash Distance Results:")
    print("-" * 60)
    for f, dist in matches:
        status = "✅ MATCH" if dist <= max_dist else "❌ NO MATCH"
        print(f"{status} | {f['id']:20s} | Distance: {dist:2d} | dHash: {f['dhash'][:16]}...")

    print()
    best_match, best_dist = matches[0]
    if best_dist <= max_dist:
        print(f"✅ BEST MATCH: {best_match['id']} (distance: {best_dist})")
        print(f"   This image will be matched to fixture: {best_match['path']}")
    else:
        print(f"❌ NO MATCH FOUND")
        print(f"   Closest fixture: {best_match['id']} (distance: {best_dist}, threshold: {max_dist})")
        print(f"   💡 Suggestion: Increase OCR_DHASH_MAX_DISTANCE to {best_dist + 1} or higher")

if __name__ == "__main__":
    main()
